[package]
name = "kademlia-file-sharing"
authors = ["Tejas Sanap <sanap.tejas@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies.libp2p]
version = "0.39.1"
default-features = true
features = [ "tcp-tokio" ]
